### ISSUE TITLE
Example for events?

### ISSUE THREAD

**Issue by archae0pteryx** [MarshallOfSound/react-electron-web-view#10]
Possible to add an example of using the events in the readme? Love what you're doing here!

**Comment by archae0pteryx** [comment]
If you have a moment, is it possible to give an example of using the events? Thank you.

**Comment by MarshallOfSound** [comment]
Believe I already answered this somewhere.

```js
<WebView onWillNavigate={this._handler} />
```

Notice the camel cased event name
