### ISSUE TITLE
Unable to load preload

### ISSUE THREAD

**Issue by archae0pteryx** [MarshallOfSound/react-electron-web-view#11]
Hello there. I am trying to inject a script via the preload prop to no avail.

```
<ElectronWebView 
        src={url} 
        className="browser" 
        preload='../lib/webview/inject'  
/>
```

am i missing something here?

**Comment by MarshallOfSound** [comment]
Make it an absolute path

**Comment by archae0pteryx** [comment]
Alrighty then

**Comment by varunrayen** [comment]
Trying to use js script in preload attribute but it doesn't load. Any help?
