### ISSUE TITLE
need help on webview

### ISSUE THREAD

**Issue by ritika-s** [MarshallOfSound/react-electron-web-view#4]
I'm working on embedding a web page on an electron-react app.
Here's what I have in the component's file among other things-
let webview = require('react-electron-web-view');
& render looks liek this-
render(){
  let googleFrame = webview({id: 'googleframe' src: 'https://www.google.com'});
  return React.DOM.div({ id:"container"},
    googleFrame,
    React.DOM.button({className:'button close', onclick: this.onCloseClick()}, Close)
  )
}

it complains in run-time, says:
![screen shot 2017-01-16 at 5 01 49 pm](https://cloud.githubusercontent.com/assets/19396670/22000517/86a9b9a8-dc0d-11e6-8a3a-fe97cad2311d.png)

**Comment by MarshallOfSound** [comment]
I don't know what language / syntax you are trying to use but you are missing a comma between `'googleframe'` and `src`
