### ISSUE TITLE
New Release Request

### ISSUE THREAD

**Issue by surajreddy** [MarshallOfSound/react-electron-web-view#6]
@MarshallOfSound when do you normally make a new release?

Our project needs to use the props in this PR: https://github.com/MarshallOfSound/react-electron-web-view/pull/5 - I'm currently using a build on my fork for the project, but it would be nice to use the plugin directly.

**Comment by MarshallOfSound** [comment]
Woops missed this 😆 

Releasing now 👍

**Comment by surajreddy** [comment]
Thanks @MarshallOfSound!
